---
title: Especies de animales invertebrados
author: Juan Carlos García Estupiñán
output: 
    html_document:
        theme: cerulean
email_adress: jcge97@gmail.com
github_repo: https://github.com/Juankkar/Especies_Encontradas_GC
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
.author, .title {
    display: none;
}
#.main-container {
        #width: 100%;
        #height: 100vh;
#}
body{
    background-color: #fff3d8;
    #font-size: 1.2vw;
}
```

# **Obtener los datos de las especies**

## Descarga las fotografias de las especies colocadas en los mapas interativo.

* Clica en: [DESCARGAR IMÁGENES INVERTEBRADOS](https://www.dropbox.com/scl/fo/j8wy15nzlrpn98dkpsu6e/h?rlkey=27la6qjalew06kc9wy3cgundv&dl=1) o [DESCARGAR IMÁGENES de FLORA Y VEGETACIÓN](https://www.dropbox.com/scl/fo/z9ad8tcbh02d2zy7g7xf0/h?rlkey=yvu3gii63sfvpicsgplvbty88&dl=1) 

Las fotografías en formato JPG están nombradas con la información de las especies, mediante el uso guiones altos ("```-```") para separar la información.

* Las imágenes de invertebrados tienen la siguiente información: ```ID-Especie-Autor-Nombre común-Familia-Orden-Clase-Filo-Reino Metazoa-Género Endémico de canarias-Especie Endémica de canarias``` 

* La información de la flora y vegetación: ```ID-Especie-Autor-Nombre común-Familia-Orden-Clase-Subdivisión-División-Reino Plantae-Género Endémico de canarias-Especie Endémica de canarias``` 

Ejemplo de la de especie invertebrado:

```
AI0001-Hemicycla ethelema-(J. Mabille, 1882)--helicidae-stylommatophora-gastropoda-mollusca-metazoa-end_gen_si-end_esp_si
```

##### **Nota:** en caso de no identificar un parámetro en concreto no se añade nada entre los guiones (ej. AI0001 no tiene nombre común identificado: ```AI0001-...-autor--familia-...```). En caso de no identificarse la especie se anota como: ```"Su ID"-NO CLASIFICADO.jpg```.

En un futuro mi idea usar esta página para añadir estadísticas de las especies que voy encontrando.

<a href="./invertebrates">&#9664; Volver al mapa de invertebrados</a>  
<a href="./flora">&#9664; Volver al mapa de flora</a>  

Última actualización el `r format(lubridate::today(), "%d/%m/%Y")`  
Sitio [desarrollado](`r rmarkdown::metadata$github_repo`) por [Juan Carlos García Estupiñán](mailto:`r rmarkdown::metadata$email_adress`)